### ISSUE TITLE
Rigol DS1102E wfm voltage levels not scaled in csv?

### ISSUE THREAD

**Issue by stapelberg** [scottprahl/RigolWFM#11] opened 2020-10-10 08:03 UTC
Hey, thanks for maintaining this useful repository!

I installed RigolWFM 0.6.5 using pip.

After converting the attached `door-open.wfm` to CSV using `wfmconvert E csv door-open.wfm`, I noticed that the resulting voltage levels seem incorrect (2.88V instead of 28.8V):

```
$ head door-open.csv
X,CH 1,Start,Increment
ms, V,-3.000000e-02,5.000000e-05
-92.057200,2.88
-92.057000,2.88
-92.056800,2.88
-92.056600,2.88
```

Whereas with Rigol’s Ultrascope program on Windows, I see the expected voltage level of 28V DC, and the program displays the 10V/div setting I used when capturing:
![door-open-screen](https://user-images.githubusercontent.com/55506/95649747-5978b600-0adf-11eb-8ad4-31753860ead0.png)

I tried loading the file into kaitai, but couldn’t see anything obviously misinterpreted—maybe it’ll be apparent to you? :)

![kaitai](https://user-images.githubusercontent.com/55506/95649792-a6f52300-0adf-11eb-9b3b-3d5dbfed2c65.jpg)

Find `door-open.wfm` in [door-open.zip](https://github.com/scottprahl/RigolWFM/files/5358617/door-open.zip) and feel free to use it as a sample file.

**Comment by scottprahl** [comment] 2020-10-10 16:26
Good catch!  It turns out you have provided the first test file that uses a 10X probe.  I checked in a fix, but I do not know if it is correct.  The issue is whether the 10X probe affects both the scale and the offset or just the vertical scale.  As implemented `door-open.wfm` now gives values around 28V.

Please `git pull` or insert this after line 210 in `channel.py` 

    self.volts *= self.probe_value

and test this fix with (with a 10X probe) for a couple of known offsets. 

If the fix works then I will release a new version.

**Comment by stapelberg** [comment] 2020-10-10 16:29
Thanks for the prompt fix. I hereby confirm that commit https://github.com/scottprahl/RigolWFM/commit/4dea20c94cccc164a1a8d770f1c580763b240e66 makes the voltage levels come out as expected! :)

**Comment by scottprahl** [comment] 2020-10-10 20:43
Try out the new release.  If it works, I will close this issue

**Comment by stapelberg** [comment] 2020-10-10 21:32
Confirmed version 0.6.6 is working fine! Thanks for the new release

**Closed as completed** 2020-10-12 18:36 UTC
